import {readFileSync} from 'node:fs'
import {expect,test,type Page} from '../../apps/web/tests/playwright'
const password='Browser-test-only-2026!'
async function login(page:Page){await page.goto('/sign-in');await page.getByLabel('用户名',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill(process.env.ONE_NVR_E2E_ADMIN_PASSWORD || password);const accepted=page.waitForResponse(r=>r.url().endsWith('/api/v1/auth/login')&&r.request().method()==='POST');await page.getByRole('button',{name:'登录',exact:true}).click();expect((await accepted).status()).toBe(200);await expect(page.getByRole('heading',{name:'总览',exact:true})).toBeVisible()}
test('plain save and export round trip keep the permanent channel and do not enable it',async({page})=>{
 await login(page);await page.goto('/channels/configure')
 await expect(page.getByRole('heading',{name:'通道配置',exact:true})).toBeVisible()
 await page.getByLabel('IP 地址',{exact:true}).fill('192.168.33.20')
 await page.getByLabel('用户名',{exact:true}).fill('fixture-camera')
 await page.getByLabel('密码',{exact:true}).fill('fixture-source-password')
 await page.getByRole('button',{name:'仅保存',exact:true}).click()
 await expect(page.getByText('已保存，未启用')).toBeVisible()
 // Save and enable are separate actions: saving alone must leave the slot
 // unapplied, even though nothing is done here to disable the enable button.
 await expect(page.getByRole('button',{name:'测试并启用',exact:true})).toBeEnabled()
 const before=await page.evaluate(async()=>{const channels=await fetch('/api/v1/channels').then(r=>r.json()).then(r=>r.data);const id=channels.items[0].id;return await fetch(`/api/v1/channels/${id}/source/status`).then(r=>r.json()).then(r=>r.data)})
 expect(before.current_revision_id).toBeNull()
 await page.getByRole('button',{name:'历史与诊断',exact:true}).click()
 await page.getByRole('button',{name:'查看账号密码',exact:true}).click()
 await expect(page.getByLabel('已保存密码',{exact:true})).toHaveValue('fixture-source-password')
 await page.getByRole('button',{name:'隐藏账号密码',exact:true}).click()
 await expect(page.getByLabel('已保存密码',{exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'查看账号密码',exact:true}).click()
 await page.getByLabel('选择通道',{exact:true}).click()
 await page.getByRole('option').nth(1).click()
 await expect(page.getByLabel('已保存密码',{exact:true})).toHaveCount(0)
 await page.goto('/channels')
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出摄像头配置',exact:true}).click();const download=await downloadPromise
 expect(download.suggestedFilename()).toBe('one-nvr-channels.json')
 const exported=readFileSync((await download.path())!)
 await page.getByRole('button',{name:'批量导入',exact:true}).click()
 await page.getByLabel('文件格式').click()
 await page.getByRole('option',{name:'JSON（one-nvr 导出）'}).click()
 await page.getByLabel('导入配置文件',{exact:true}).setInputFiles({name:'one-nvr-channels.json',mimeType:'application/json',buffer:exported})
 await page.getByRole('button',{name:'生成导入预览',exact:true}).click()
 await expect(page.getByText('第 1 行 · 已跳过')).toBeVisible()
 await expect(page.getByRole('button',{name:'确认并应用选中行',exact:true})).toBeDisabled()
 // No secret is stored in local/session storage; exported source is intentionally current-only.
 expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('fixture-source-password')
 const after=await page.evaluate(async()=>{const channels=await fetch('/api/v1/channels').then(r=>r.json()).then(r=>r.data);return await fetch(`/api/v1/channels/${channels.items[0].id}/source/status`).then(r=>r.json()).then(r=>r.data)})
 expect(after.channel_id).toBe(before.channel_id);expect(after.current_revision_id).toBeNull()
})

test('CSV preview uses real API, reports empty rows and preserves current media state',async({page})=>{
 await login(page);await page.goto('/channels')
 await page.getByRole('button',{name:'批量导入',exact:true}).click()
 const csv='channel_no,channel_name,ip,rtsp_port,username,password,main_path,sub_path\n1,大门,192.168.33.20,554,fixture,fixture-pass,/main,/sub\n2,空通道,,,,,,\n'
 await page.getByLabel('导入配置文件',{exact:true}).setInputFiles({name:'channels.csv',mimeType:'text/csv',buffer:Buffer.from(csv)})
 await page.getByRole('button',{name:'生成导入预览',exact:true}).click()
 await expect(page.getByText('预览已生成，尚未测试或应用')).toBeVisible()
 await expect(page.getByText('第 1 行 · 待确认')).toBeVisible()
 await expect(page.getByText('第 2 行 · 已跳过')).toBeVisible()
 await expect(page.getByText('空源行已跳过，保留原配置')).toBeVisible()
 await expect(page.getByRole('button',{name:'确认并应用选中行',exact:true})).toBeDisabled()
 await page.getByRole('link',{name:'恢复此批任务',exact:true}).click()
 await expect(page.getByText('批任务已恢复，请查看逐行结果')).toBeVisible()
 await expect(page.getByText('第 1 行 · 待确认')).toBeVisible()
 await expect(page.getByRole('button',{name:'确认并应用选中行',exact:true})).toBeDisabled()
 expect(await page.evaluate(()=>document.body.innerText)).not.toContain('fixture-pass')
 expect(await page.evaluate(async()=>{const channels=await fetch('/api/v1/channels').then(r=>r.json()).then(r=>r.data);return await fetch(`/api/v1/channels/${channels.items[0].id}/source/status`).then(r=>r.json()).then(r=>r.data.current_revision_id)})).toBeNull()
})


test('late actual draft response cannot replace another selected channel',async({page})=>{
 await login(page);await page.goto('/channels/configure')
 let release:()=>void=()=>{},received:()=>void=()=>{}
 const delivered=new Promise<void>(resolve=>{received=resolve}),gate=new Promise<void>(resolve=>{release=resolve})
 await page.route('**/source-revisions',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();received();await gate;await route.fulfill({response})})
 await page.getByLabel('IP 地址',{exact:true}).fill('192.168.33.21')
 await page.getByLabel('密码',{exact:true}).fill('late-draft-fixture-password')
 await page.getByRole('button',{name:'保存并启用',exact:true}).click()
 await delivered
 await page.getByLabel('选择通道',{exact:true}).click()
 await page.getByRole('option').nth(1).click()
 release()
 await expect(page.getByLabel('IP 地址',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('密码',{exact:true})).toHaveValue('')
 await expect(page.getByText('已保存，未启用')).toHaveCount(0)
})

test('viewer cannot access source configuration or credentials',async({page})=>{
 const username='m1b-viewer-'+Date.now()
 await login(page);await page.goto('/users')
 await page.getByLabel('新用户名',{exact:true}).fill(username)
 await page.getByLabel('初始密码',{exact:true}).fill(password)
 await page.getByLabel('角色',{exact:true}).click()
 await page.getByRole('option',{name:'查看者',exact:true}).click()
 await page.getByRole('button',{name:'创建账号',exact:true}).click()
 await expect(page.getByText('账号已创建',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:`${username} 的通道权限`,exact:true}).click()
 await page.getByLabel('CH01 实时',{exact:true}).check()
 await page.getByRole('button',{name:'保存通道权限',exact:true}).click()
 await expect(page.getByText('权限已保存',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'用户菜单',exact:true}).click()
 await page.getByRole('menuitem',{name:'退出登录',exact:true}).click()
 await page.getByLabel('用户名',{exact:true}).fill(username);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click()
 await expect(page.getByRole('heading',{name:'总览',exact:true})).toBeVisible()
 await page.goto('/channels/configure')
 await expect(page.getByRole('alert')).toContainText('没有权限')
 await expect(page.getByRole('button',{name:'查看账号密码',exact:true})).toHaveCount(0)
 await page.goto('/channels');await expect(page.getByRole('link',{name:/^配置 CH/})).toHaveCount(0)
})
