import { readFile, writeFile } from 'node:fs/promises'
import openapiTS, { astToString } from 'openapi-typescript'

const apiRoot = new URL('../../../docs/api/', import.meta.url)
const foundation = JSON.parse(await readFile(new URL('m1a.openapi.yaml', apiRoot), 'utf8'))
const extension = JSON.parse(await readFile(new URL('m1b.openapi.yaml', apiRoot), 'utf8'))

// M1-B is standalone through external foundation schema references; after
// composition those references have the same canonical local definitions.
function localize(value) {
  if (Array.isArray(value)) return value.map(localize)
  if (!value || typeof value !== 'object') return value
  return Object.fromEntries(Object.entries(value).map(([key, entry]) => [
    key,
    key === '$ref' && typeof entry === 'string' && entry.startsWith('m1a.openapi.yaml#/')
      ? entry.slice('m1a.openapi.yaml'.length)
      : localize(entry),
  ]))
}
const combined = structuredClone(foundation)
const extra = localize(extension)
for (const [path, methods] of Object.entries(extra.paths)) {
  for (const method of Object.keys(methods)) {
    if (combined.paths[path]?.[method]) throw new Error(`Duplicate API operation: ${method} ${path}`)
  }
  combined.paths[path] = { ...combined.paths[path], ...methods }
}
for (const [name, schema] of Object.entries(extra.components.schemas)) {
  if (combined.components.schemas[name]) throw new Error(`Duplicate API schema: ${name}`)
  combined.components.schemas[name] = schema
}
combined.info = { ...foundation.info, title: 'one-nvr M1 API contract', version: extension.info.version }
const output = astToString(await openapiTS(combined))
await writeFile(new URL('../src/lib/api-types.ts', import.meta.url),
  '/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n' + output)
